#!/usr/bin/env /bin/bash

version=$(curl --silent "https://api.github.com/repos/datalevin/datalevin/tags" | jq -r '.[0].name')

wget https://github.com/datalevin/datalevin/releases/download/$version/dtlv-$version-ubuntu-22.04-amd64.zip
wget https://github.com/datalevin/datalevin/releases/download/$version/dtlv-$version-macos-14-aarch64.zip

linux="dtlv-$version-ubuntu-22.04-amd64.zip"
macos_aarch64="dtlv-$version-macos-14-aarch64.zip"

linux_sha=$(sha256sum "$linux" | cut -f 1 -d " ")
macos_aarch64_sha=$(sha256sum "$macos_aarch64" | cut -f 1 -d " ")

sed -e "s/\${i}/1/" -e "s/\${VERSION}/$version/g" \
    -e "s/\${LINUX_SHA}/$linux_sha/g" \
    -e "s/\${MACOS_AARCH64_SHA}/$macos_aarch64_sha/g" \
    datalevin.template > Formula/datalevin.rb
